variables:
  LAYER_01: "01_core_infra"
  LAYER_02: "02_observability"
  LAYER_03: "03_landing_zone"

stages:
  - test

default:
  image: 
    name: hashicorp/terraform:latest
    entrypoint: [""]

# -----main branchのみ: terraform validateを実行-----
main_validate_job:
  stage: test
  before_script:
    - echo "Adding execute permission to scripts"
    - chmod +x $CI_PROJECT_DIR/pipeline/scripts/*
    - echo "Changing directory to:" $TARGET_LAYER
    - pwd; ls -a
    - cd terraform/$TARGET_LAYER/env/dev

  script:
    - $CI_PROJECT_DIR/pipeline/scripts/validate.sh $TARGET_LAYER

  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" # マージリクエスト後（Merge前）のみ実行
      changes:
        - "terraform/$TARGET_LAYER/**/*"  # 指定されたレイヤーのディレクトリ配下が変更された時だけ実行

  parallel:
    matrix:
      - TARGET_LAYER: [$LAYER_01, $LAYER_02, $LAYER_03]

# -----feature branchのみterraform planを実行-----
feature_plan_job:
  stage: test
  before_script:
    - echo "Adding execute permission to scripts"
    - chmod +x $CI_PROJECT_DIR/pipeline/scripts/*
    - echo "Changing directory to:" $TARGET_LAYER
    - echo $TF_TOKEN_app_terraform_io
    - pwd; ls -a
    - cd terraform/$TARGET_LAYER/env/dev

  script:
    - $CI_PROJECT_DIR/pipeline/scripts/feature_plan.sh $TARGET_LAYER

  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^feature\//'
      changes:
        - "terraform/$TARGET_LAYER/**/*"  # 指定されたレイヤーのディレクトリ配下が変更された時だけ実行

  parallel:
    matrix:
      - TARGET_LAYER: [$LAYER_01, $LAYER_02, $LAYER_03]